[toolchain]
# TODO: don't require nightly (see
# https://github.com/keep-starknet-strange/snos/issues/462)
channel = "nightly-2024-09-05"
components = ["rust-src", "rustfmt", "clippy", "rust-analyzer"]
profile = "minimal"
