name: Task - Orchestrator Linters

on:
  workflow_dispatch:
  workflow_call:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run prettier
        working-directory: orchestrator
        run: |-
          npx prettier --check .

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: avto-dev/markdown-lint@v1
        with:
          config: "orchestrator/.markdownlint.json"
          args: "orchestrator"
          ignore: "orchestrator/target"

  toml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Download taplo
        run: |
          curl -L https://github.com/tamasfe/taplo/releases/download/0.9.3/taplo-linux-x86_64.gz -o taplo.gz
          gunzip taplo.gz
          chmod +x taplo
          mv taplo /usr/local/bin/taplo
      - name: Checkout toml files
        uses: actions/checkout@v4
      - name: Run toml check
        working-directory: orchestrator
        run: taplo fmt --config ../taplo/taplo.toml --check
