name: "Changelog Workflow (Orchestrator)"
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]
    paths:
      - "orchestrator/"

jobs:
  # Enforces the update of a changelog file on every pull request
  # skipLabel default is "Skip-Changelog"
  changelog-orchestrator:
    runs-on: ubuntu-latest
    steps:
      - uses: dangoslen/changelog-enforcer@v3
        with:
          changeLogPath: "orchestrator/CHANGELOG.md"
