---
name: Task - Run check

on:
  workflow_dispatch:
  workflow_call:

jobs:
  rust_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "cache"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.81

      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.8.2"

      - name: Check the project
        run: |
          cargo check --release --workspace --exclude orchestrator
